saveDESCRIPTION <- function(name){
  fields <- data.frame(
    Package = name,
    Type="Session",
    Version = as.character(utils::packageVersion('opencpu')),
    Author = "OpenCPU",
    Date = as.character(Sys.Date()),
    Description = "This file is automatically generated by OpenCPU.",
    stringsAsFactors = FALSE
  )
  write.dcf(fields, file = "DESCRIPTION")
}
