saveDESCRIPTION <- function(name){
  fields <- data.frame(
    Package = name, 
    Type="Session", 
    Version = "1.0",
    Author = "OpenCPU",
    Date = as.character(as.Date(Sys.time())),
    Description = "This file is automatically generated by OpenCPU.",
    stringsAsFactors = FALSE
  )
  write.dcf(fields, file = "DESCRIPTION")
}
